### PR TITLE
Add java.lang.Iterable instance for wgl/Op.

### PR DESCRIPTION
**Pull request by stevana**
Fixes: https://github.com/jepsen-io/jepsen/issues/439
Supersedes: https://github.com/jepsen-io/knossos/pull/33

### CODE REVIEW

**Comment by aphyr** [comment]
(haven't merged this yet just cuz I'm not sure this is actually correct behavior--need to check and write tests for it)

**Comment by aphyr** [comment]
OK, yeah, this is not correct behavior. We should be returning a seq of mapentries here.

**Comment by stevana** [comment]
Updated, does that look better?

**Comment by aphyr** [comment]
Yeah, that oughta do!

**Pull request merged**
